### ISSUE TITLE
please create new releases/tags

### ISSUE THREAD

**Issue by Phil-Friderici** [eoly/puppet-rancid#12]
Hi @eoly,
it would be helpfull for us if you could create new releases/tags when updating your module. With this it's easier to explicit choose which version to use :)

Thanks & have phun
Phil

**Comment by eoly** [comment]
I'll work on that. Thanks

**Comment by Phil-Friderici** [comment]
Thanks a lot :) If you need any help or advice, please let me know.

have phun & a nice weekend
Phil

**Comment by eoly** [comment]
Tagged and released version 0.1.4 to the forge.

**Comment by ghoneycutt** [comment]
I wouldn't bother with forge updates until your module is 1.0.0.

Maybe @Phil-Friderici knows someone new that needs experience writing spec tests :stuck_out_tongue_closed_eyes:

**Comment by Phil-Friderici** [comment]
@eoly Thank you :)
@ghoneycutt I'll ask @ejabach if he wants to take the next step with this one :smirk:
