### ISSUE TITLE
collaborator?

### ISSUE THREAD

**Issue by ghoneycutt** [eoly/puppet-rancid#21]
Hi @eoly 

Could you add me as a collaborator to this repo? This would let me push changes to it. When pushing new changes, I would tag and release them in accordance to my other modules and those of Ericsson.

**Comment by eoly** [comment]
@ghoneycutt  just added you as a collaborator

**Comment by ghoneycutt** [comment]
Thank you!

**Comment by ghoneycutt** [comment]
Strangely it seems that I still do not have access to merge.
